module.exports =
[
  {
    "Title":"Home Alone",
    "Year":"1990",
    "Rated":"PG",
    "Runtime":"103 min",
    "Genre":"Comedy, Family",
    "Plot":"An eight-year-old troublemaker must protect Christmas vacation.",
    "Poster":"https://m.media-amazon.com/images/M/MV5BMzFkM2YwOTQtYzk2Mi00N2VlLWE3NTItN2YwNDg1YmY0ZDNmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    "imdbRating":"7.6",
    "playDate": new Date('2020-5-3 5:45 PM'),
    "price": 20,
    "chairs":15,
    "availableChairs": 15,
    "movieTrailer": "https://www.youtube.com/embed/durNwe9pL0E",
    "availability": true
  },
  {
    "Title":"Home Alone",
    "Year":"1990",
    "Rated":"PG",
    "Runtime":"103 min",
    "Genre":"Comedy, Family",
    "Plot":"An eight-year-old troublemaker must protect Christmas vacation.",
    "Poster":"https://m.media-amazon.com/images/M/MV5BMzFkM2YwOTQtYzk2Mi00N2VlLWE3NTItN2YwNDg1YmY0ZDNmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    "imdbRating":"7.6",
    "playDate": new Date('2020-5-3 5:45 PM'),
    "price": 20,
    "chairs":15,
    "availableChairs": 15,
    "movieTrailer": "https://www.youtube.com/embed/durNwe9pL0E",
    "availability": true
  },
  {
    "Title":"Home Alone",
    "Year":"1990",
    "Rated":"PG",
    "Runtime":"103 min",
    "Genre":"Comedy, Family",
    "Plot":"An eight-year-old troublemaker must protect Christmas vacation.",
    "Poster":"https://m.media-amazon.com/images/M/MV5BMzFkM2YwOTQtYzk2Mi00N2VlLWE3NTItN2YwNDg1YmY0ZDNmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    "imdbRating":"7.6",
    "playDate": new Date('2020-5-3 5:45 PM'),
    "price": 20,
    "chairs":15,
    "availableChairs": 15,
    "movieTrailer": "https://www.youtube.com/embed/durNwe9pL0E",
    "availability": true
  },
  {
    "Title":"Home Alone",
    "Year":"1990",
    "Rated":"PG",
    "Runtime":"103 min",
    "Genre":"Comedy, Family",
    "Plot":"An eight-year-old troublemaker must protect Christmas vacation.",
    "Poster":"https://m.media-amazon.com/images/M/MV5BMzFkM2YwOTQtYzk2Mi00N2VlLWE3NTItN2YwNDg1YmY0ZDNmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    "imdbRating":"7.6",
    "playDate": new Date('2020-5-3 5:45 PM'),
    "price": 20,
    "chairs":15,
    "availableChairs": 5,
    "movieTrailer": "https://www.youtube.com/embed/durNwe9pL0E",
    "availability": true
  },
  {
    "Title":"Home Alone",
    "Year":"1990",
    "Rated":"PG",
    "Runtime":"103 min",
    "Genre":"Comedy, Family",
    "Plot":"An eight-year-old troublemaker must protect Christmas vacation.",
    "Poster":"https://m.media-amazon.com/images/M/MV5BMzFkM2YwOTQtYzk2Mi00N2VlLWE3NTItN2YwNDg1YmY0ZDNmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    "imdbRating":"7.6",
    "playDate": new Date('2020-5-3 5:45 PM'),
    "price": 20,
    "chairs":15,
    "availableChairs": 15,
    "movieTrailer": "https://www.youtube.com/embed/durNwe9pL0E",
    "availability": true
  },
  {
    "Title":"Home Alone",
    "Year":"1990",
    "Rated":"PG",
    "Runtime":"103 min",
    "Genre":"Comedy, Family",
    "Plot":"An eight-year-old troublemaker must protect Christmas vacation.",
    "Poster":"https://m.media-amazon.com/images/M/MV5BMzFkM2YwOTQtYzk2Mi00N2VlLWE3NTItN2YwNDg1YmY0ZDNmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    "imdbRating":"7.6",
    "playDate": new Date('2020-5-3 5:45 PM'),
    "price": 20,
    "chairs":15,
    "availableChairs": 15,
    "movieTrailer": "https://www.youtube.com/embed/durNwe9pL0E",
    "availability": true
  },
  {
    "Title":"Home Alone",
    "Year":"1990",
    "Rated":"PG",
    "Runtime":"103 min",
    "Genre":"Comedy, Family",
    "Plot":"An eight-year-old troublemaker must protect Christmas vacation.",
    "Poster":"https://m.media-amazon.com/images/M/MV5BMzFkM2YwOTQtYzk2Mi00N2VlLWE3NTItN2YwNDg1YmY0ZDNmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    "imdbRating":"7.6",
    "playDate": new Date('2020-5-3 5:45 PM'),
    "price": 20,
    "chairs":15,
    "availableChairs": 15,
    "movieTrailer": "https://www.youtube.com/embed/durNwe9pL0E",
    "availability": true
  }
]
